# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    entity.management:
            class: AppBundle\Services\EntityManagement
            arguments: [~ , "@doctrine.orm.entity_manager"]
            tags:
             - { name: entity.management }
    curl.request:
                class: AppBundle\Services\CurlRequest
                arguments: [~]
                tags:
                 - { name: curl.request }
#    app.exception_listener:
#            class: AppBundle\EventListener\ExceptionListener
#            tags:
#                - { name: kernel.event_listener, event: kernel.exception }
    app.post_listener:
                class: AppBundle\EventListener\PostListener
                arguments: ["@entity.management"]
                tags:
                    - { name: post_event }
