# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    entity.management:
            class: AppBundle\Services\EntityManagement
            arguments: [~ , "@doctrine.orm.entity_manager"]
            tags:
             - { name: entity.management }
